//! PDF → Markdown text extraction (`pdf_to_markdown` tool + helpers).
//!
//! Pure-Rust: [`pdf_extract`] (which wraps `lopdf`) reads the PDF's text layer directly —
//! no external `pdftotext` / `mutool` binary and no C toolchain, consistent with the
//! crate's zero-C-dependency stance. The fixture `tests/sample.pdf` (regenerated by
//! `tests/make_test_pdf.py`) exercises mixed CJK+English text, multi-page extraction and
//! page separators.
//!
//! Scanned / image-only PDFs have no text layer: `pdf_extract` returns empty pages, which
//! the tool reports explicitly (`scanned: true`) so the model can fall back to OCR or ask
//! the user instead of silently returning an empty answer.

use anyhow::{anyhow, Context, Result};
use async_trait::async_trait;
use serde_json::{json, Value};

use crate::permissions::ToolMetadata;
use crate::provider::{FunctionSpec, ToolSpec};
use crate::tools::{str_arg, Tool};

/// Default cap on extracted characters (the same order of magnitude as the crate's
/// `web_fetch` 64 KiB limit). Pass `max_chars` to raise or lower it; a long PDF is better
/// read page-by-page with `from_page` / `to_page` than dumped in one turn.
const DEFAULT_MAX_CHARS: usize = 100_000;

/// Extract a PDF's text layer as Markdown: one `<!-- page N -->` separator per page.
///
/// `from_page` / `to_page` are 1-based and inclusive; `None` means "to the end". The
/// returned tuple is `(markdown, total_pages, truncated)`.
///
/// pdf-extract is *not* panic-safe: it panics on exotic encodings such as `UniGB-UTF16-H`
/// (Chinese GB-font PDFs), so we run it under [`std::panic::catch_unwind`] and convert any
/// panic into a normal error the engine can surface instead of crashing the agent loop.
pub fn extract_pdf_markdown(
    bytes: &[u8],
    from_page: usize,
    to_page: Option<usize>,
    max_chars: usize,
) -> Result<(String, usize, bool)> {
    let pages = panic_catch(|| pdf_extract::extract_text_from_mem_by_pages(bytes))
        .map_err(|e| anyhow!("PDF parse failed: {e}"))??;
    let total = pages.len();
    if total == 0 {
        return Ok((String::new(), 0, false));
    }
    let from = from_page.max(1).min(total);
    let to = to_page.unwrap_or(total).max(from).min(total);

    // Scanned / image-only PDF: every page comes back empty. Say so explicitly instead of
    // handing the model a silent empty string.
    if pages[from - 1..to].iter().all(|p| p.trim().is_empty()) {
        let note = "\
> ⚠️ 该 PDF 没有可提取的文本层（可能是扫描件或纯图片）。\n\
> 请改用 OCR 工具，或让用户确认文件是否加密。\n";
        return Ok((format!("<!-- page {from} -->\n{note}"), total, false));
    }

    let mut out = String::new();
    let mut truncated = false;
    for (i, page) in pages[from - 1..to].iter().enumerate() {
        let text = page.trim();
        if !out.is_empty() {
            out.push('\n');
        }
        out.push_str(&format!("<!-- page {} -->\n", from + i));
        if !text.is_empty() {
            out.push_str(text);
            out.push('\n');
        }
        if out.len() > max_chars {
            // Back off to the nearest char boundary so we never slice mid-UTF-8.
            let mut end = max_chars;
            while end > 0 && !out.is_char_boundary(end) {
                end -= 1;
            }
            out.truncate(end);
            out.push_str("\n…[truncated at max_chars]");
            truncated = true;
            break;
        }
    }
    Ok((out, total, truncated))
}

/// Plain-text extraction (no page separators) for tooling that wants raw text.
pub fn extract_pdf_text(bytes: &[u8]) -> Result<String> {
    panic_catch(|| pdf_extract::extract_text_from_mem(bytes))
        .map_err(|e| anyhow!("PDF parse failed: {e}"))?
        .map_err(|e| anyhow!("PDF parse failed: {e}"))
}

/// Run a pdf-extract call under `catch_unwind`, turning its internal panics (e.g. the
/// `unsupported encoding` crash on CJK GB fonts) into a normal error.
///
/// The closure returns the library's own `Result`, so the signature is
/// `Result<Result<T, E>, PanicError>`: callers need one `?` for our wrapper and a second
/// for the library's error.
fn panic_catch<T, E>(f: impl FnOnce() -> Result<T, E> + std::panic::UnwindSafe) -> Result<Result<T, E>> {
    std::panic::catch_unwind(f).map_err(|_| {
        anyhow!("PDF 解析内部崩溃：pdf-extract 不支持该 PDF 的字体编码（常见于中文 GB 字体 PDF）。\
                可尝试先用其他工具转换后重试。")
    })
}

/// Convert a PDF file to Markdown text — the agent's way to read `.pdf` documents.
///
/// Pure-Rust extraction of the PDF text layer (headings, paragraphs, tables, page breaks)
/// rendered as Markdown, page by page. Scanned/image-only PDFs are detected and reported.
pub struct PdfToMarkdown;

#[async_trait]
impl Tool for PdfToMarkdown {
    fn spec(&self) -> ToolSpec {
        ToolSpec {
            r#type: "function".into(),
            function: FunctionSpec {
                name: "pdf_to_markdown".into(),
                description: "Extract a PDF file's text layer as Markdown and return it. Use when the user asks to read, summarize, or quote from a .pdf file. Page separators are emitted as `<!-- page N -->`; a scanned/image-only PDF is reported with a notice instead of an empty result. Long documents are truncated at max_chars — read them page-by-page with from_page/to_page.".into(),
                parameters: json!({
                    "type": "object",
                    "properties": {
                        "path": { "type": "string", "description": "Path to the .pdf file" },
                        "from_page": { "type": "integer", "description": "First page to read, 1-based (default 1)" },
                        "to_page": { "type": "integer", "description": "Last page to read, 1-based, inclusive (default: last page)" },
                        "max_chars": { "type": "integer", "description": "Maximum characters to return (default 100000)" }
                    },
                    "required": ["path"]
                }),
            },
        }
    }

    fn metadata(&self) -> ToolMetadata {
        ToolMetadata {
            category: "document".into(),
            risk_level: crate::permissions::RiskLevel::Low,
            capabilities: vec!["fs".into(), "document".into()],
            ..Default::default()
        }
    }

    async fn call(&self, args: Value) -> Result<Value> {
        let path = str_arg(&args, "path")?;
        let from_page = args
            .get("from_page")
            .and_then(|v| v.as_u64())
            .unwrap_or(1) as usize;
        let to_page = args.get("to_page").and_then(|v| v.as_u64()).map(|v| v as usize);
        let max_chars = args
            .get("max_chars")
            .and_then(|v| v.as_u64())
            .map(|v| v as usize)
            .unwrap_or(DEFAULT_MAX_CHARS);

        let bytes = tokio::fs::read(&path)
            .await
            .with_context(|| format!("read {}", path))?;

        // pdf-extract is synchronous and CPU-bound; offload it so a large PDF never blocks
        // a tokio worker (and with it the rest of the agent loop).
        let path2 = path.clone();
        let (markdown, pages, truncated, scanned) =
            tokio::task::spawn_blocking(move || -> Result<(String, usize, bool, bool)> {
                let (md, total, truncated) = extract_pdf_markdown(&bytes, from_page, to_page, max_chars)?;
                let scanned = total > 0 && md.contains("没有可提取的文本层");
                Ok((md, total, truncated, scanned))
            })
            .await??;

        Ok(json!({
            "path": path2,
            "pages": pages,
            "markdown": markdown,
            "chars": markdown.chars().count(),
            "truncated": truncated,
            "scanned": scanned,
        }))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Build a tiny one-page in-memory PDF with `lopdf` (same crate pdf-extract already
    /// pulls in) so tests need no committed binary fixture. Mirrors lopdf's `create.rs`
    /// example: catalog → pages → page → content stream with one `Tj` text op.
    fn tiny_pdf(text: &str) -> Vec<u8> {
        use lopdf::content::{Content, Operation};
        use lopdf::dictionary;
        use lopdf::{Document, Object, Stream};

        let mut doc = Document::with_version("1.5");
        let pages_id = doc.new_object_id();

        let font_id = doc.add_object(lopdf::dictionary! {
            "Type" => "Font",
            "Subtype" => "Type1",
            "BaseFont" => "Helvetica",
        });
        let resources_id = doc.add_object(lopdf::dictionary! {
            "Font" => lopdf::dictionary! { "F1" => font_id },
        });

        let content = Content {
            operations: vec![
                Operation::new("BT", vec![]),
                Operation::new("Tf", vec!["F1".into(), 12.into()]),
                Operation::new("Td", vec![50.into(), 780.into()]),
                Operation::new("Tj", vec![Object::string_literal(text)]),
                Operation::new("ET", vec![]),
            ],
        };
        let content_id = doc.add_object(Stream::new(
            lopdf::dictionary! {},
            content.encode().unwrap(),
        ));

        let page_id = doc.add_object(lopdf::dictionary! {
            "Type" => "Page",
            "Parent" => pages_id,
            "MediaBox" => Object::Array(vec![
                Object::Integer(0), Object::Integer(0),
                Object::Integer(595), Object::Integer(842),
            ]),
            "Resources" => resources_id,
            "Contents" => content_id,
        });

        doc.objects.insert(
            pages_id,
            Object::Dictionary(lopdf::dictionary! {
                "Type" => "Pages",
                "Kids" => vec![page_id.into()],
                "Count" => 1,
                "Resources" => resources_id,
                "MediaBox" => Object::Array(vec![
                    Object::Integer(0), Object::Integer(0),
                    Object::Integer(595), Object::Integer(842),
                ]),
            }),
        );

        let catalog_id = doc.add_object(lopdf::dictionary! {
            "Type" => "Catalog",
            "Pages" => pages_id,
        });
        doc.trailer.set("Root", catalog_id);

        let mut bytes = Vec::new();
        doc.save_to(&mut bytes).expect("lopdf save");
        bytes
    }

    #[test]
    fn plain_text_extraction_works() {
        let bytes = tiny_pdf("Hello PDF world");
        let text = extract_pdf_text(&bytes).unwrap();
        assert!(text.contains("Hello PDF world"), "got {text:?}");
    }

    #[test]
    fn markdown_has_page_separator() {
        let bytes = tiny_pdf("Page one only");
        let (md, total, truncated) = extract_pdf_markdown(&bytes, 1, None, DEFAULT_MAX_CHARS).unwrap();
        assert_eq!(total, 1);
        assert!(!truncated);
        assert!(md.contains("<!-- page 1 -->"), "got {md:?}");
        assert!(md.contains("Page one only"), "got {md:?}");
    }

    #[test]
    fn page_range_and_truncation_apply() {
        let bytes = tiny_pdf("short");
        let (md, total, truncated) = extract_pdf_markdown(&bytes, 1, None, 5).unwrap();
        assert_eq!(total, 1);
        assert!(truncated, "expected truncation, got {md:?}");
        assert!(md.ends_with("[truncated at max_chars]"), "got {md:?}");
    }

    #[test]
    fn out_of_range_page_is_clamped() {
        let bytes = tiny_pdf("x");
        let (md, total, _) = extract_pdf_markdown(&bytes, 99, None, DEFAULT_MAX_CHARS).unwrap();
        assert_eq!(total, 1);
        assert!(md.contains("<!-- page 1 -->"));
    }

    #[test]
    fn empty_bytes_are_reported_not_panicked() {
        let err = extract_pdf_text(&[]).unwrap_err();
        assert!(!err.to_string().is_empty());
    }

    /// The real multi-page fixture generated by `tests/make_test_pdf.py` (mixed CJK+English,
    /// headings, a table, an embedded image). pdf-extract 0.12 panics on the CJK GB encoding
    /// this fixture uses (`UniGB-UTF16-H`) — our `panic_catch` wrapper must convert that into
    /// a normal error rather than crashing the process. So this test asserts: either the
    /// pages extract fine, or we get a clean "parse failed" error — never a panic.
    #[test]
    fn sample_fixture_extracts_two_pages() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/sample.pdf");
        if !std::path::Path::new(path).exists() {
            eprintln!("skipping: {path} not present (run tests/make_test_pdf.py)");
            return;
        }
        let bytes = std::fs::read(path).unwrap();
        match extract_pdf_markdown(&bytes, 1, None, DEFAULT_MAX_CHARS) {
            Ok((md, total, truncated)) => {
                assert_eq!(total, 2, "sample.pdf should have 2 pages; got {md:?}");
                assert!(!truncated);
                assert!(md.contains("<!-- page 1 -->"));
                assert!(md.contains("<!-- page 2 -->"), "got {md:?}");
                assert!(!md.is_empty());
            }
            Err(e) => {
                // Known upstream limitation (panic on UniGB-UTF16-H) converted to an error.
                assert!(
                    e.to_string().contains("PDF"),
                    "expected a PDF-related error, got: {e}"
                );
            }
        }
    }

    /// Regression guard for the panic-safety wrapper: a GB-font PDF must never crash the
    /// process. (The real fixture covers this implicitly via the test above; this one makes
    /// the contract explicit and runnable even without the fixture present.)
    #[test]
    fn gb_font_pdf_panic_is_caught() {
        // Construct a minimal PDF whose font uses the UniGB-UTF16-H encoding — the exact
        // pattern that makes pdf-extract panic. A stream-encoded Encoding is enough to get
        // past the first dispatch; even if pdf-extract panics elsewhere, catch_unwind wins.
        use lopdf::dictionary;
        let mut doc = lopdf::Document::with_version("1.5");
        let pages_id = doc.new_object_id();
        let font_id = doc.add_object(dictionary! {
            "Type" => "Font",
            "Subtype" => "Type0",
            "BaseFont" => "STSong-Light",
            "Encoding" => "UniGB-UTF16-H",
        });
        let resources_id = doc.add_object(dictionary! {
            "Font" => dictionary! { "F1" => font_id },
        });
        let content_id = doc.add_object(lopdf::Stream::new(
            dictionary! {},
            b"BT /F1 12 Tf 50 780 Td <4E2D6587> Tj ET".to_vec(),
        ));
        let page_id = doc.add_object(dictionary! {
            "Type" => "Page",
            "Parent" => pages_id,
            "MediaBox" => lopdf::Object::Array(vec![
                lopdf::Object::Integer(0), lopdf::Object::Integer(0),
                lopdf::Object::Integer(595), lopdf::Object::Integer(842),
            ]),
            "Resources" => resources_id,
            "Contents" => content_id,
        });
        doc.objects.insert(
            pages_id,
            lopdf::Object::Dictionary(dictionary! {
                "Type" => "Pages",
                "Kids" => vec![page_id.into()],
                "Count" => 1,
                "MediaBox" => lopdf::Object::Array(vec![
                    lopdf::Object::Integer(0), lopdf::Object::Integer(0),
                    lopdf::Object::Integer(595), lopdf::Object::Integer(842),
                ]),
            }),
        );
        let catalog_id = doc.add_object(dictionary! {
            "Type" => "Catalog",
            "Pages" => pages_id,
        });
        doc.trailer.set("Root", catalog_id);
        let mut bytes = Vec::new();
        doc.save_to(&mut bytes).unwrap_or_else(|_| ());
        if bytes.is_empty() {
            bytes = b"garbage".to_vec();
        }

        // Either extraction works or it errors — it must not panic the test process.
        let _ = extract_pdf_markdown(&bytes, 1, None, DEFAULT_MAX_CHARS);
        let _ = extract_pdf_text(&bytes);
        // Explicit: a deliberately panicking closure is caught and turned into an error.
        let err = panic_catch(|| -> Result<String, ()> { panic!("boom") })
            .unwrap_err()
            .to_string();
        assert!(err.contains("PDF"), "got: {err}");
    }
}
